### ISSUE TITLE
Des-selección de parámetros controlados por audio

### ISSUE THREAD

**Issue by tenderbolton** [nperi/N.IMP#1]
No encontré ninguna opción para des-seleccionar un parámetro que ya está reaccionando a audio.

Tal vez una buena opción sería listar los parámetros que responden a audio dentro del nodo del audio con posibilidad de eliminarlos.

**Comment by MiliGaricoits** [comment]
Para que un parametro deje de recibir como entrada un audio, hay q hacer click en el boton "Editar" del nodo audio correspondiente. Luego todos los parametros que estan conectados a ese audio se pintaran de otro color, y haciendo click sobre el parametro se des-selecciona. Despues se hace click en "Editar" de nuevo y el cambio queda guardado.

**Comment by tenderbolton** [comment]
Ok, esa modalidad está OK.

De todas formas al probarlo tuve un comportamiento extraño:

1- Guardo un patcher que tiene parámetros que reaccionan a audio.
2- Cierro y abro de nuevo ese patcher.
3- Despliego la interfaz de audio y la de un nodo que tenga parámetros controlados por audio.
4- Presiono Edit en el nodo de audio, y no se pinta el parámetro que reacciona.

Si además apago edit sin tocar nada, los parámetros dejan de reaccionar a audio.

**Comment by MiliGaricoits** [comment]
Si, ese issue quedo arreglado en un commit de ayer.
Debería estar andando ahora si tenes lo ultimo. 
Confirmame cuando puedas si te sigue pasando.

**Comment by tenderbolton** [comment]
El último commit no me compila:

/Users/cclark/Documents/Devel/cpp/of_v0.8.4_osx_releaseNIMP/apps/NIMPgit/farq2014/src/NodeViewer.cpp:56:74: Too many arguments to function call, expected single argument 'active_', have 2 arguments

/Users/cclark/Documents/Devel/cpp/of_v0.8.4_osx_releaseNIMP/apps/NIMPgit/farq2014/src/NodeViewer.cpp:66:75: Too many arguments to function call, expected single argument 'active_', have 2 arguments

/Users/cclark/Documents/Devel/cpp/of_v0.8.4_osx_releaseNIMP/apps/NIMPgit/farq2014/src/NodeViewer.cpp:76:66: Too many arguments to function call, expected single argument 'active_', have 2 arguments

**Comment by MiliGaricoits** [comment]
Fueron commits en varios repos

https://github.com/MiliGaricoits/ofxGui_nimp
https://github.com/MiliGaricoits/ofxComposer_nimp
