### ISSUE TITLE
Saturación de AudioAnalizer y Audio Input

### ISSUE THREAD

**Issue by tenderbolton** [nperi/N.IMP#10]
Es muy probable que NIMP se use en un lugar con música o ruido muy altos.

Actualmente si uno está en un ambiente con mucho ruido, los nodos de audio de NIMP se saturan rápidamente.

En la implementación anterior, NIMP tenía un parámetro para reducir o aumentar en nivel de volumen de la entrada de audio.

Creo que es importante tener lo mismo en la interfaz. Esto podría ponerse en cada nodo.

**Comment by MiliGaricoits** [comment]
Se le puede cambiar la saturacion a los nodos Audio in y Audio Analizer desde el inspector de cada nodo.

fixed in 97e66bf419259d2ab80e30de40c4ce271df6ae8d

and fa2c005197414cc3f6e39e8defb77cf77292f145 of https://github.com/MiliGaricoits/ofxFilterbank_nimp.git

**Comment by MiliGaricoits** [comment]
Los nodos de tipo audio también se puede habilitar o deshabilitar.

0b812347552a299d8113dd8e7af994ca119fb220
