### ISSUE TITLE
Al cambiar en nombre de un nodo no se cambia su nombre en la GUI

### ISSUE THREAD

**Issue by tenderbolton** [nperi/N.IMP#12]
Lo probé con un nodo de cámara.

1- Creo el nodo.
2- Abro su interfaz.
3- Cambio el nombre y presiono enter.
4- Cierro la interfaz.

El nombre del nodo en la GUI sigue siendo "New Camera"

**Comment by MiliGaricoits** [comment]
fixed on 23c3919639e779c01467701e2e899cfacb89480d
