### ISSUE TITLE
Límite a scale de nodos

### ISSUE THREAD

**Issue by tenderbolton** [nperi/N.IMP#13]
Me ha pasado varias veces que un nodo me queda demasiado grande o demasiado pequeño y desaparece de la interfaz.

Habría que poner un límite al scale que puede hacer el usuario al arrastrar un vértice del nodo.

**Comment by nperi** [comment]
Esto fue resuelto, queda el issue https://github.com/nperi/N.IMP/issues/34 respecto al tema
