### ISSUE TITLE
Opciones de ventana de nodo no responden al click en el lugar donde deberían

### ISSUE THREAD

**Issue by tenderbolton** [nperi/N.IMP#14]
Parecería haber un desplazamiento entre la letra de la opción y el objeto que responde al evento click.

Probé en el Image Processor. En el nodo cámara parecería no darse (pero no estoy seguro).
Subo video para que se entienda.

[NIMP_GUIOptionsDisplacementH264.mov.zip](https://github.com/nperi/N.IMP/files/177961/NIMP_GUIOptionsDisplacementH264.mov.zip)

**Comment by MiliGaricoits** [comment]
fixed on bb29eb021ad6f7146a1d121d8d7e599c743353ae and
commit 848d43edc8b3bd935802a66eaf719448d681bcbe on  https://github.com/MiliGaricoits/ofxComposer_nimp
