### ISSUE TITLE
Hacer scroll mueve las barras de títulos y opciones de los nodos

### ISSUE THREAD

**Issue by tenderbolton** [nperi/N.IMP#15]
![screen shot 2016-03-17 at 9 23 58 pm](https://cloud.githubusercontent.com/assets/7373873/13865121/c85970b8-ec86-11e5-88c0-4e98316d168a.png)

**Comment by MiliGaricoits** [comment]
fixed on commit 7a226f54250ef98b4d5dc227f114dcad08cd7cdc for https://github.com/MiliGaricoits/ofxComposer_nimp.git
