### ISSUE TITLE
Reapertura - Opciones de ventana de nodo no responden al click en el lugar donde deberían

### ISSUE THREAD

**Issue by tenderbolton** [nperi/N.IMP#17]
Este problema sigue ocurriendo.

Por lo que vi, pasa en todos los nodos, y se debe al zoom.

1- Crear un nodo cámara.
2- Apretar la opción "i" 2 veces para abrir y cerrar la interfaz y corroborar que el click reacciona OK.
3- Con la interfaz cerrada hacer zoom.
4- Intentar presionar nuevamente la opción "i"

**Comment by MiliGaricoits** [comment]
Yo no lo puedo seguir reproduciendo. Adjunto video.
Hiciste pull de ambos proyectos? NIMP y https://github.com/MiliGaricoits/ofxComposer_nimp ??

[issue #17.zip](https://github.com/nperi/N.IMP/files/178910/issue.17.zip)

**Comment by tenderbolton** [comment]
Me faltaba un pull en ofxComposer_nimp.

Cuando hice el pull de NIMP no estaba disponible en nuevo commit del Composer.

Ahora esto está OK.
