### ISSUE TITLE
Nodo Video e Imágenes

### ISSUE THREAD

**Issue by tenderbolton** [nperi/N.IMP#18]
En la versión anterior de NIMP había un tipo de nodo llamado ImageInputList (ImageInputList.h y .cpp).

Si bien en un principio se había implementado un nodo exclusivo para video (el VideoPlayerMac), éste se dejó de usar porque usaba un player por nodo y generaba un consumo excesivo de CPU.

Entonces, para controlar mejor la cantidad de players simultáneos, se creó la entidad VideoPool. VideoPool es un pool de videoplayers a donde los nodos de NIMP solicitan una instacia de un playe cuando lo necesitan.

El nodo ImageInputList sustituyó a VideoPlayerMac porque además de reproducir imágenes (una lista de imágenes) puede también reproducir video.

Si se fijan n el código el nodo ImageInputList soporta reproducir ImageTypes, y entre los ImageTypes está ImageTypeMovie (que termina siendo una imagen).

El nodo ImageInputList soporta reproducir una lista de ImageTypes, qu pueden ser fotos o videos.

Es importante que se use ese nodo y no el VideoPlayerMac, por lo tanto propongo que eliminen el nodo video actual, y dejen sólo el imageinputlist (tal vez cambiándole el nombre a Image and Video en la GUI).

La GUI del nodo ImageInputList tendría que soportar que el usuario cree la lista de elementos a reproducir, y que la pueda editar.

**Comment by MiliGaricoits** [comment]
Christian,

te parece eliminar el nodo video? Si se quieren mezclar dos entradas distintas de imagenes o videos igual van a existir varias instancias del video player.

Al momento, la manera de agregarle mas imagenes o videos al nodo ImageInputList, es haciendo drag de un archivo y drop sobre el nodo ImageInputList. Capaz se puede agregar un boton en el inspector del nodo para agregar mas imagenes o videos, por que al momento, el file explorer solo deja seleccionar un archivo. Es decir, no podemos seleccionar varias imagenes al mismo tiempo al crear el nodo.

**Comment by tenderbolton** [comment]
Milagros,

1- Sí, creo que deberíamos eliminar el nodo video.

Tengan en cuenta que el VideoPool se hizo justamente para que si tenemos muchos nodos de video, entonces la cantidad total de videoplayers siempre sea la misma (los que están dentro del pool).

Esto implica que todos los nodos de video comparten los videoplayers del Pool (el VideoPool es un objeto único en la aplicación... no sé si está definido como Singleton, pero podría estarlo).

2- Con respecto a lo de los archivos, el Drag and drop está OK. Pero habría que poner algo en la GUI que indique que se puede draggear hasta el nodo, porque de lo contrario no queda claro para el usuario cómo debería hacerlo.

Tal vez poner una imagen como la usada en algunas páginas que demarcan la zona de recepción del drag.

OK con lo del selector.

¿Se puede elegir el orden de los archivos dentro del nodo una vez que son cargados con drag?

**Comment by MiliGaricoits** [comment]
Dale, sacamos el nodo entonces y mejoramos la manera de agregar videos/imagenes.
VideoPool es un singleton si.
Las imagenes y videos quedan en el orden en que fueron ingresados. Se pueden eliminar con el boton "Delete current sequence".

**Comment by tenderbolton** [comment]
Estuve revisando la parte de drag and drop.

Lo que sí pude hacer es arrastrar un video a nimp, y el video se convirtió en un nodo de "image video", lo que está muy bueno.

Sin embargo, no encontré la forma de agregar un video a la lista de reproducción de un nodo pre-existente (los nodos soportan listas, y poder pasar de un video a otro es una funcionalidad que se usa bastante).

**Comment by MiliGaricoits** [comment]
Va un video que muestra como se hace con drag&drop. 
Igual vamos a agregar la opcion de hacerlo desde el inspector del nodo.

[imagelist.zip](https://github.com/nperi/N.IMP/files/181415/imagelist.zip)

**Comment by MiliGaricoits** [comment]
fixed in f44e52ba61f81b9a3fc834f95259219661ab1730
