### ISSUE TITLE
Selección de control de parámetros

### ISSUE THREAD

**Issue by tenderbolton** [nperi/N.IMP#19]
Esto lo comprobé con los nodos de audio, peor puede extrapolarse a cualquier nodo de control donde la interfaz permita seleccionar los parametros que se desea controlar.

Lo que sucede es que si creo dos nodos de audio puedo editar los parámetros que controlan ambos al mismo tiempo (prendiendo el Edit de ambos nodos).

Esto no debería permitirse, esto implica que si algún nodo está editando sus parámetros, los demás nodos no deben dejar establecer su edición.

**Comment by MiliGaricoits** [comment]
fixed in 6678979
