### ISSUE TITLE
Problema al al borrar un nodo de audio cuando se está editando sus parámetros controlados

### ISSUE THREAD

**Issue by tenderbolton** [nperi/N.IMP#2]
Si se crea un nodo de audio y se comienza a editar los parámetros de otros nodos que controla, y luego con el "editar" prendido el usuario borra el nodo audio, se da una situación extraña en la que los parámetros que uno clickea siguen pintándose de amarillo (como si estuvieran siendo seleccionados para que sean controlados por el nodo audio que dejó de existir).

**Comment by MiliGaricoits** [comment]
fixed in 4df24c289bc96827094cc25cc112f4a45d6e3906
