### ISSUE TITLE
Agrandar o achicar nodos dejó de funcionar

### ISSUE THREAD

**Issue by tenderbolton** [nperi/N.IMP#20]
Estaba haciendo un proyecto de prueba y noté que no puedo agrandar o achicar nodos.

Va video.
[NIMP_GUIExpandNodeH264-2.mov.zip](https://github.com/nperi/N.IMP/files/181089/NIMP_GUIExpandNodeH264-2.mov.zip)

**Comment by MiliGaricoits** [comment]
fixed in c5c89e5b909451304eb4560cfc99d3164d457b84 & [d30bd56](https://github.com/MiliGaricoits/ofxComposer_nimp/commit/d30bd5688e4e947bd78f1f64089c5916448ae16d)  for https://github.com/MiliGaricoits/ofxComposer_nimp
