### ISSUE TITLE
Nodo de VideoPlayer desaparece cuando se acciona un nodo switch

### ISSUE THREAD

**Issue by tenderbolton** [nperi/N.IMP#21]
Cuando un camino de procesamiento se apaga, se está apagando el nodo video.

Esto puede no ser un error, pero es inconsistente con lo que pasa con los demás nodos (el resto de los nodos que vi no se apagan).

Acá tenemos que tomar una decisión:
1- Por un lado, está bueno que los nodos se "apaguen", porque aliviana el procesamiento de la máquina y ayuda a mantener el framerate.

2- Por otro lado, si apagamos los nodos no podemos ver cómo se está procesando la imagen resultante de ese camino.

Creo que la mejor solución es un mix de las dos, o sea, darle al usuario la posibilidad de prender o apagar un camino de procesamiento que está switcheado off.

¿Qué les parece?

**Comment by tenderbolton** [comment]
Va video.
[NIMP_GUIVideoPlayerDesapareceConSwitch.mov.zip](https://github.com/nperi/N.IMP/files/181092/NIMP_GUIVideoPlayerDesapareceConSwitch.mov.zip)

**Comment by MiliGaricoits** [comment]
Christian,

Esta bueno darle la opción al usuario. Tener un boton que sea "Apagar inactivos" o algo asi. Por que al estar conectados a un multi channel switch es probable que no se usen en otro camino de procesamiento y si se apaga, mejora la performance.

Vi que los headers de los nodos se te ven desfazados. Eso ya deberia estar arreglado.

**Comment by tenderbolton** [comment]
Coincido. Esa opción debería estar en el nodo switch.

Sí, los títulos se mueven cuando hago scroll. Antes de probar hoy me aseguré de tener las últimas versiones de los repos, pero puede que haya pifeado en algo. Mañana lo verifico de nuevo.

**Comment by MiliGaricoits** [comment]
fixed in 4ba42623142db1709a8c54ecc2b0c3e531e322a8
