### ISSUE TITLE
Es difícil borrar conexiones entre nodos

### ISSUE THREAD

**Issue by tenderbolton** [nperi/N.IMP#22]
Un nodo origen puede estar conectado a muchos nodos destin, y actualmente las conexiones entre nodos sólo pueden borrarse todas juntas dando click en el pequeño círculo de salida o llegada de la conexión.

Eso hace que a veces cuando se quiere borrar una sola conexión uno termine borrando muchas que no desea borrar.

Habría que elegir otra dinámica de eliminación de conexiones, tal vez seleccionándolas o atravesándolas con el mouse a modo de "corte".

**Comment by MiliGaricoits** [comment]
Control + Click sobre el link te parece bien? Misma idea que para borrar vertices de los links.

**Comment by tenderbolton** [comment]
Puede ser...tal vez la tecla "alt option" sea más nemotécnica (por lo de alterno o alterar).

No entiendo el comentario de borrar vértices de los links. ¿Es una funcionalidad existente?

**Comment by MiliGaricoits** [comment]
Te adjunto un video.
Haciendo click sobre el link se agrega un nuevo vertice, y haciendo click+control sobre el vertice se elimina

[linkdots.mp4.zip](https://github.com/nperi/N.IMP/files/181371/linkdots.mp4.zip)

**Comment by tenderbolton** [comment]
Entiendo, esa funcionalidad está muy bien.

Pero no usaría Control porque el usuario podría borrar links sin querer cuando se queda sin puntos intermedios.

Iría por Alt Option para borrar los links directamente.

**Comment by MiliGaricoits** [comment]
fixed in [[00a58c3]](https://github.com/MiliGaricoits/ofxComposer_nimp/commit/00a58c34b55bfdfc5ffeb6f80ad70275cdfcd214) ofxComposer_nimp

**Comment by tenderbolton** [comment]
¿Cómo se hace para borrar conexiones ahora?

**Comment by MiliGaricoits** [comment]
los links con "Alt Option" y los vertices de los links con Control

**Comment by tenderbolton** [comment]
Estoy haciendo lo siguiente:

1- Creo un nodo cámara, y un nodo image processor.
2- Los un con una conexión.
3- Apreto AltOption y doy click en el link.

Y no se borra.

**Comment by MiliGaricoits** [comment]
fixed in [7fe3650](https://github.com/MiliGaricoits/ofxComposer_nimp/commit/7fe3650676530b03d405c787b5358602ced6b1fe) ofxComposer_nimp
