### ISSUE TITLE
Encapsulamiento de nodos acepta conexión entrante.

### ISSUE THREAD

**Issue by tenderbolton** [nperi/N.IMP#23]
Hice la prueba de encapsular varios nodos, y noté que si los encapsulo puedo hacer una conexión de entrada al nodo encapsulado. Esto creo que no debería poder hacerse.

Van imágenes de antes de encapsular y después de encapsular y conectar una entrada.

![screen shot 2016-03-19 at 6 42 38 pm](https://cloud.githubusercontent.com/assets/7373873/13902063/dfc17c40-ee17-11e5-9852-380a9070be20.png)
![screen shot 2016-03-19 at 6 43 08 pm](https://cloud.githubusercontent.com/assets/7373873/13902064/e37335b8-ee17-11e5-9829-f98e73bcf656.png)
![screen shot 2016-03-19 at 6 43 21 pm](https://cloud.githubusercontent.com/assets/7373873/13902065/e8522454-ee17-11e5-927c-99c814b4fa91.png)

**Comment by MiliGaricoits** [comment]
No se dibuja el input cuando es un encapsulado.

 [[9384b09]](https://github.com/MiliGaricoits/ofxComposer_nimp/commit/9384b09dce4a863c7921a8fae5f98ac3b871f428)  for https://github.com/MiliGaricoits/ofxComposer_nimp

**Comment by tenderbolton** [comment]
Ok, imagino que si no se dibuja implica que la conexión no se hizo.
