### ISSUE TITLE
Nodo de audio input debería mostrar información de la banda seleccionada

### ISSUE THREAD

**Issue by tenderbolton** [nperi/N.IMP#24]
Cuando se está seleccionando la onda es difícil darse cuenta cómo reaccionan las diferentes bandas antes de que los parámetros empiecen a reaccionar.

Esto se soluciona mostrando la información de la banda en vez de la onda sin filtrar por FFT.

**Comment by MiliGaricoits** [comment]
las informacion de las bandas, aplicando FFT se muestra en el nodo Audio Analizer. En los Audio in se muestra la onda del sonido

**Comment by MiliGaricoits** [comment]
Ahora el nodo audio in se dibuja con un graph en el tiempo que solo muestra los cambios del sonido en la banda seleccionada.

Va video que muestra como los parámetros son afectados según el nivel del sonido y la banda.
[audio.mp4.zip](https://github.com/nperi/N.IMP/files/220229/audio.mp4.zip)

commits [9397501](https://github.com/MiliGaricoits/ofxUI_nimp) y [f4738ae](https://github.com/nperi/N.IMP)
