### ISSUE TITLE
Comportamiento de parámetro Sound Saturation

### ISSUE THREAD

**Issue by tenderbolton** [nperi/N.IMP#25]
El parámetro Sound Saturation tiene unn par comportamientos extraños:

1- Ví que a medida que aumento el parámetro se apaga la onda. Esto es contra intuitivo, porque el usuario esperaría que al aumentarlo la onda aumente.

2- No pude lograr que la onda se apagara completamente. Me refiero a hacerlo completamente insensible al audio. En el esquema actual, si pongo el nodo al máximo no debería ver que la onda se mueve (sin embargo, sería mejor contemplar lo que dice el punto 1 y hacer que la onda se apague cuando el parámetro está en cero).

**Comment by MiliGaricoits** [comment]
fixed in 75f0157
