### ISSUE TITLE
Intentar conectar nodos a veces dispara la herramienta de selección

### ISSUE THREAD

**Issue by tenderbolton** [nperi/N.IMP#26]
Va foto (el cuadrado con la diagonal es la mezcla de la herramienta de selección y la nueva conexión).

![screen shot 2016-03-19 at 6 24 20 pm](https://cloud.githubusercontent.com/assets/7373873/13902598/365eee88-ee2d-11e5-8aee-132974c41c09.png)

**Comment by nperi** [comment]
En la ultima version esta arreglado
