### ISSUE TITLE
Por lo que veo los nodos pueden no estar controlando su cantidad de inputs

### ISSUE THREAD

**Issue by tenderbolton** [nperi/N.IMP#27]
Hoy pude conectar dos nodos como entrada de un Image Processor (que debería tener una única entrada).

Esto tal vez se esté dando en otros tipos de nodo.

**Comment by MiliGaricoits** [comment]
fixed in d48aa3b & [1556657](https://github.com/MiliGaricoits/ofxComposer_nimp/commit/1556657b4bb63d2ab662c86b3fe1ef66d892c53b)
