### ISSUE TITLE
Utilización de flechas teclado en creación de nodo

### ISSUE THREAD

**Issue by tenderbolton** [nperi/N.IMP#29]
Sería útil poder utilizar las teclas UP y DOWN durante la creación de un nodo.

Cuando estoy creando un nodo siempre apreto N y las primeras letras del nodo, luego instintivamente Down para ir a seleccionarlo.

**Comment by MiliGaricoits** [comment]
fixed in edf45f6 & [ff1b5da](https://github.com/MiliGaricoits/ofxUI_nimp/commit/ff1b5dad8e84acba84674c0352d4cfced93d07a7)
