### ISSUE TITLE
Tamaño máximo del canvas debería ser un poco más grande (o zoom out más poderoso)

### ISSUE THREAD

**Issue by tenderbolton** [nperi/N.IMP#30]
Hoy me pasó que en un proyecto con 10 nodos me saturó la pantalla (no tenía más lugar ni con el zoom out al máximo).

Tal vez deberíamos considerar aumentar el tamaño de área útil un 50% más.

**Comment by nperi** [comment]
Vamos a hacer un zoom out más poderoso.
Igualmente, lo que es el área útil no está limitada, si se arrastra un nodo contra algún borde de la pantalla se van actualizando los scroll bars, pudiendo tener más espacio.

**Comment by nperi** [comment]
fixed
