### ISSUE TITLE
Algunos tipos de nodo no tienen la opción ENABLE en su interfaz

### ISSUE THREAD

**Issue by tenderbolton** [nperi/N.IMP#31]
Por ejemplo los Blend y los Switches.

Habría que revisar por qué esto está así.

**Comment by MiliGaricoits** [comment]
Se le agrego el enable a los que faltaba. El multi channel switch no se si tiene mucho sentido que tenga un enable. No aplica ninguna transformación.

fixed in c336b1ecdbad435cea7285688f81c84ff7df298d
