### ISSUE TITLE
Consulta sobre diseño

### ISSUE THREAD

**Issue by tenderbolton** [nperi/N.IMP#33]
Noté que la forma de incluir addons en NIMP a veces implica entrar al addon y modificarlo.

Veo que lo han hecho en casi todos los addons usados.

¿Por qué optaron por hacer esto y no por heredar de las clases que debían modificar?

**Comment by MiliGaricoits** [comment]
Decidimos crearnos un fork de esos addons y cambiar el codigo que necesitabamos, para q quede mas prolijo. 
Los cambios en los addons no eran chicos y eran en muchas clases. En un principio lo hicimos extendiendo las clases, hasta que vimos que crecia muchisimo el codigo, q estabamos reescribiendo muchas cosas y el codigo quedaba repartido por varios lados.

**Comment by tenderbolton** [comment]
Ok.
