### ISSUE TITLE
HAP y versión de OpenGL

### ISSUE THREAD

**Issue by tenderbolton** [nperi/N.IMP#36]
Estuve revisando el tema de HAP, y no le he encontrado la vuelta aún.

Deberíamos empezar a debatir entre los beneficios de trabajar con esta versión de OpenGL para decidir si vamos a la versión estándar y así poder usar el HAP Player.

Según lo que tengo entendido, esta versión de OpenGL sólo se usa porque necesitamos una nueva ventana para la consola. ¿Esto es correcto?

Si es sólo eso, entonces propongo incorporar la consola a la ventana principal de NIMP, se podría hace una sección de consola colapsable a modo de franja vertical en la parte derecha de la pantalla donde se muestran los mensajes. Y se desplegaría y ocultaría con un botón en la barra de opciones superior o en la lateral. Algo en esta zona:
![zona consola](https://cloud.githubusercontent.com/assets/7373873/13905530/2c2a1810-eea1-11e5-8593-bbfbfb441daa.png)

**Comment by nperi** [comment]
Se cambió de versión de OpenGL para poder soportar abrir varias ventanas, esto es la consola y las ventanas que se abran de los nodos encapsulados.

Volver a la versión anterior de OpenGL implicaría perder esas funcionalidades, además de volver atrás todos los cambios necesarios para que nimp y los diferentes addons funcionen con esta versión de OpenGL y esas funcionalidades (por ejemplo, el manejo de eventos en las diferentes clases, ver de que ventana provienen).
