### ISSUE TITLE
Zoom sigue activo cuando se presiona el mouse.

### ISSUE THREAD

**Issue by tenderbolton** [nperi/N.IMP#5]
Por lo que vi el comportamiento es el siguiente:
1. Si se hace click y luego se arrastra entonces el comportamiento es el esperado y el zoom no acciona.
2. Pero si tengo el dedo apoyado en el trackpad, y luego con otro dedo hago click para arrastrar un parámetro o un nodo, entonces ahí el zoom sigue activo.

**Comment by tenderbolton** [comment]
Tal vez el caso sea que estoy haciendo click mientras estoy haciendo zoom (el zoom vino antes que el click). En esta situación deberíamos apagar el zoom y tomar en cuenta sólo el click.

Esto debería resolverse fácil con alguna variable que indique si el usuario está haciendo click.

**Comment by nperi** [comment]
Estuve intentando reproducirlo y no puedo.
Podés detallar un poco mejor los pasos para reproducirlo?

**Comment by tenderbolton** [comment]
Hay que usar el mouse con 2 dedos y se reproduce fácil.

**Comment by tenderbolton** [comment]
Tengan en cuenta que mi configuración de click secundario en mi mac es "click in bottom right corner".

Las macs suelen venir con una configuración que es "Click with two fingers".

Mi configuración hace posible que pueda dar click a algo y luego arrastrar, o clickear mientras tengo un segundo dedo apoyado en el trackpad, algo que con la configuración estándar no se puede.

**Comment by tenderbolton** [comment]
Aquí va la formula para reproducir.
1. Configurar el trackpad en "click in bottom corner" para hacer click secundario.
2. Crear un nodo image processor.
3. Abrir la interfaz.
4. ir a un parámetro de barra y dar click con un solo dedo en el trackpad (en la zona de clickeo) y dejarlo apretado.
5. Sin soltar ese dedo apoyar otro y tratar de hacer zoom. 

NIMP no debería hacer zoom, porque el click está apretado, y de todas formas lo hace igual.

Va video.
[NIMP_ZoomActivationH264.mov.zip](https://github.com/nperi/N.IMP/files/180325/NIMP_ZoomActivationH264.mov.zip)

**Comment by nperi** [comment]
Fixed on 4f7e53874c5ec827d736fe8acdd24b2557393838
