### ISSUE TITLE
Error al presionar New Patcher

### ISSUE THREAD

**Issue by tenderbolton** [nperi/N.IMP#6]
NIMP abortó ejecución una vez que presioné New Patcher.

Lo que hice fue crear un nodo cámara, luego un image processor, luego un audio in, y luego asignar algunos parámetros a audio.

Luego salvé el patcher.

Y por último presioné New Patcher y ahí se disparó el error. Estoy intentando reproducirlo, pero por ahora no pude.

**Comment by tenderbolton** [comment]
Lo que sí sé es que el error se dio dentro de la threaded function de ParamInputGenerator, en la línea 81: processInput();

Lo que puede estar pasando, es que al borrar un nodo que tienen threads no se están deteniendo correctamente sus hilos. Eso explicaría por qué a veces se da y a veces no.

**Comment by nperi** [comment]
fixed on d5914e9ac4bc9f8b5cc32715be521e8c7e498b67
