### ISSUE TITLE
Error al conectar un simple mix como entrada de otro simple mix.

### ISSUE THREAD

**Issue by tenderbolton** [nperi/N.IMP#9]
Estaba haciendo un patcher que era algo así:

CAM ---> IMG Proc ---> Simple MIx --------> Simple MIX
                                            ^                               ^
IMG ----> IMGP Proc    ------|                               |
                                                                            |
VIDEO -----------------------------------------------------|

Y nimp abortó ejecución tirando el siguiente stack trace:

Thread 1Queue : com.apple.main-thread (serial)
#0  0x000d13e9 in MixSimpleBlend::resetSizeBasedOnInput(ofxPatch*) at /Users/cclark/Documents/Devel/cpp/of_v0.8.4_osx_releaseNIMP/apps/NIMPgit/farq2014/src/Mixer/MixSimpleBlend.cpp:230
#1  0x001f6efe in ImageOutput::addInput(ofxPatch*) at /Users/cclark/Documents/Devel/cpp/of_v0.8.4_osx_releaseNIMP/apps/NIMPgit/farq2014/src/ImageOutput.cpp:54
#2  0x001e72be in ofxComposer::connect(int, int, int, bool) at /Users/cclark/Documents/Devel/cpp/of_v0.8.4_osx_releaseNIMP/addons/ofxComposer_nimp/src/ofxComposer.cpp:652
#3  0x001e436b in ofxComposer::_mouseReleased(ofMouseEventArgs&) at /Users/cclark/Documents/Devel/cpp/of_v0.8.4_osx_releaseNIMP/addons/ofxComposer_nimp/src/ofxComposer.cpp:394

![screen shot 2016-03-14 at 10 49 41 am](https://cloud.githubusercontent.com/assets/7373873/13746506/851e179c-e9d2-11e5-8741-d4e0715426a2.png)

**Comment by MiliGaricoits** [comment]
Issue was fixed in commit 0540052843afb0779fdaabb7f6d50f2ac1d1a601
